GET http://localhost:3000/users
Content-Type: application/json

###

POST http://localhost:3000/users
Content-Type: application/json

#condition: email must unique and password must be more than 8 length

{
  "name": "Hamzah Raihan",
  "email": "hamzah@gmail.com",
  "password": "123456780"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "name": "Hamzah Raihan",
  "email": "hamzah@gmail.com",
  "password": "123456780"
}