### Get all todos
GET http://localhost:3000/todos
Content-Type: application/json

### Post Todo
POST http://localhost:3000/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbGlpbmRpYUBnbWFpbC5jb20iLCJpZCI6IjY1NGY3MjNjNjc3MTM1YmM0MWIwMTQ1ZSIsImlhdCI6MTY5OTcwNTQwNywiZXhwIjoxNjk5NzkxODA3fQ.rXz3UYNifywaSpP07Sxt_-ZafD1pV1j7e_vuEAlyxSo
Content-Type: application/json

{
  "todo": "Halo",
  "IsComplete": false,
  "userId": "654e2fa56941e1e7af6b1e02"
}

### Get todo by id
GET http://localhost:3000/todos/654f386d87666723fedbc854
Content-Type: application/json

### Edit Todo
PUT http://localhost:3000/todos/654f386d87666723fedbc854
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbGlpbmRpYUBnbWFpbC5jb20iLCJpZCI6IjY1NGY3MjNjNjc3MTM1YmM0MWIwMTQ1ZSIsImlhdCI6MTY5OTcwNTQwNywiZXhwIjoxNjk5NzkxODA3fQ.rXz3UYNifywaSpP07Sxt_-ZafD1pV1j7e_vuEAlyxSo
Content-Type: application/json

{
  "todo": "Halo edited",
  "isComplete": true
}

### Delete Todo
DELETE  http://localhost:3000/todos/654f73b0677135bc41b01471
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbGlpbmRpYUBnbWFpbC5jb20iLCJpZCI6IjY1NGYzZGI4Mzg5MGMzYTQ5ZGM3YjJiOCIsImlhdCI6MTY5OTcwMzU2MywiZXhwIjoxNjk5Nzg5OTYzfQ.WILJLKOkRqEpqdnmeb-BTe3T3A8NFltA71cQLN1L_aI
Content-Type: application/json